package com.medicalml.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing an early warning health alert.
 * Maps to the "early_warnings" database table.
 *
 * Warnings are generated by the ML pipeline's risk scoring engine (Layer 6)
 * when a patient's biomarker values exceed clinical thresholds or their
 * overall risk score is elevated.
 *
 * Warnings remain active until explicitly acknowledged by a clinician via the
 * API.
 */
@Entity
@Table(name = "early_warnings")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EarlyWarning {

    /** Auto-generated UUID primary key. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Foreign key linking this warning to the patient. */
    @Column(name = "patient_id", nullable = false)
    private UUID patientId;

    /**
     * Foreign key linking this warning to the specific checkup record that
     * triggered it.
     */
    @Column(name = "record_id")
    private UUID recordId;

    /**
     * Type of warning. Examples:
     * - "HIGH_RISK_SCORE" — Overall ML risk score exceeded 0.7.
     * - "MODERATE_RISK" — Risk score between 0.5 and 0.7.
     * - "BIOMARKER_DEVIATION_GLUCOSE" — Glucose level significantly deviates from
     * normal.
     */
    @Column(name = "warning_type", nullable = false, length = 100)
    private String warningType;

    /** Severity level: "LOW", "MEDIUM", or "HIGH". */
    @Column(nullable = false, length = 20)
    private String severity;

    /**
     * Human-readable description of the warning (e.g., specific biomarker deviation
     * details).
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;

    /**
     * Clinical recommendation for the attending physician (e.g., suggested
     * follow-up tests).
     */
    @Column(columnDefinition = "TEXT")
    private String recommendation;

    /**
     * Timestamp when this warning was generated by the ML pipeline. Defaults to
     * now.
     */
    @Column(name = "triggered_at", nullable = false)
    @Builder.Default
    private LocalDateTime triggeredAt = LocalDateTime.now();

    /**
     * Whether a clinician has reviewed and acknowledged this alert. Defaults to
     * false.
     */
    @Column(nullable = false)
    @Builder.Default
    private Boolean acknowledged = false;

    /** Timestamp when the alert was acknowledged. Null until acknowledged. */
    @Column(name = "acknowledged_at")
    private LocalDateTime acknowledgedAt;
}
