package com.medicalml.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * JPA entity storing latent health indices computed from dimensionality
 * reduction.
 * Maps to the "latent_indices" database table.
 *
 * Generated by ML pipeline Layer 3 (Ref-1):
 * - PCA produces linear projections capturing the most variance in biomarker
 * data.
 * - Autoencoder produces non-linear embeddings via a neural network.
 * - Composite scores aggregate domain-level risks (metabolic, cardiovascular,
 * organ function).
 *
 * These latent representations are used by clustering and risk scoring
 * algorithms.
 */
@Entity
@Table(name = "latent_indices")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LatentIndex {

    /** Auto-generated UUID primary key. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Foreign key linking to the CheckupRecord that generated these indices. */
    @Column(name = "record_id", nullable = false)
    private UUID recordId;

    /**
     * PCA components stored as JSONB.
     * Contains the principal component values and explained variance ratios.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "pca_index", columnDefinition = "jsonb")
    private Map<String, Object> pcaIndex;

    /**
     * Autoencoder latent embedding stored as JSONB.
     * 16-dimensional vector from the bottleneck layer of the neural network.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "autoencoder_embedding", columnDefinition = "jsonb")
    private Map<String, Object> autoencoderEmbedding;

    /**
     * Metabolic composite score (glucose, HbA1c, cholesterol, lipids).
     * Higher values indicate greater metabolic risk.
     */
    @Column(name = "metabolic_composite", precision = 8, scale = 4)
    private BigDecimal metabolicComposite;

    /**
     * Cardiovascular composite score (blood pressure, heart rate).
     * Higher values indicate greater cardiovascular risk.
     */
    @Column(name = "cardiovascular_composite", precision = 8, scale = 4)
    private BigDecimal cardiovascularComposite;

    /**
     * Organ function composite score (liver enzymes, kidney markers).
     * Higher values indicate greater organ function impairment risk.
     */
    @Column(name = "organ_function_composite", precision = 8, scale = 4)
    private BigDecimal organFunctionComposite;

    /** Timestamp when these indices were computed. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
